#################################
# CDR3 vs VJ-sepcific expansion #
#################################

# Required libraries: 
library (tidyverse)
library (ggraph)
library (igraph)
library (gridExtra)

# Performs z-test to evaluate if expansion is dependent on a specific CDR3 or VJ
# @param patient: Patient desired for analysis
# @param cohort: Sample cohort desired for analysis
# @param clones: Clones to be isolated (TIL, background, all)
# @param comp_samp: Sample to compare growth from (bl_df or inf_df)
# @param step2_output_filename: Filename for step 2 file
# @param step2_output_datapath: Datapath for step 2 file

CDR3vsVJ_expansion <- function(patient, cohort, clones, comp_samp, step2_output_filename, step2_output_datapath){

    # Creates dataframe comparing a CDR3's growth and its corresponding VJ-growth
    for(patient in patients){
        timepoint_order <- c("baseline_apheresis", "infusion", "4W")
        for(patient in patients){
            '%notin%' <- Negate('%in%')

            #Reading the input files:      
            #Concatenated file generated by '''Step2_TRBclonotype_txtFile_concatenation.R'''
            clonotypes <- read_csv(
                    file.path(
                            step2_output_datapath , 
                            step2_output_filename
                            ), 
                    )%>% 
                    filter ( Patient_id %in% patient)%>%
                    filter ( Cohort == cohort) %>%
                    filter ( cloneCount > 1) %>%
                    mutate(VJcombo = gsub("[.]", "_", VJcombo))
                   
            clonotypes <- clonotypes[-c(grep("[*]", clonotypes$aaSeqCDR3)),]
            clonotypes <- clonotypes[-c(grep("_", clonotypes$aaSeqCDR3)),]
            for(clone in 1:length(clonotypes$cloneFraction)){
                clonotypes$cloneFraction[clone] <- clonotypes$cloneCount[clone]/sum(clonotypes[which(clonotypes$Cycle==clonotypes$Cycle[clone]),]$cloneCount)
            }

            inf_df <- clonotypes[which(clonotypes$Cycle=="infusion"),]
            bl_df <- clonotypes[which(clonotypes$Cycle=="baseline_apheresis"),]
            if(clones == "TIL"){
                bl_df <- bl_df[which(bl_df$nSeqCDR3 %in% inf_df$nSeqCDR3),]
            } 
            if(clones == "background"){
                bl_df <- bl_df[which(bl_df$nSeqCDR3 %notin% inf_df$nSeqCDR3),]
            }
            if(patient=="TLML_1_"){
                fw_df <- clonotypes[which(clonotypes$Cycle=="FU1"),]
            } else{
                fw_df <- clonotypes[which(clonotypes$Cycle=="4W"),] 
            }
            compare <- eval(as.name(comp_samp))
            for(i in 1:nrow(compare)){
                fw_match <- fw_df[which(fw_df$nSeqCDR3==compare$nSeqCDR3[i]),]
                if(length(fw_match$VJcombo)!=0){
                    if(fw_match$VJcombo!=compare$VJcombo[i]){
                        compare$VJcombo[i] <- fw_match$VJcombo
                    }
                }
            }

            VJ_growth <- data.frame(matrix(NA, ncol=1,nrow=length(unique(compare[which(compare$VJcombo %in% fw_df$VJcombo),]$VJcombo))))
            colnames(VJ_growth) <- c("Growth")
            rownames(VJ_growth) <- unique(compare[which(compare$VJcombo %in% fw_df$VJcombo),]$VJcombo)
            for(i in 1:nrow(VJ_growth)){
                fw_frac <- sum(fw_df[which(fw_df$VJcombo==rownames(VJ_growth)[i]),]$cloneFraction)
                compare_frac <- sum(compare[which(compare$VJcombo==rownames(VJ_growth)[i]),]$cloneFraction)
                VJ_growth$Growth[i] <- fw_frac/compare_frac
            }

            CDR3_growth <- data.frame(matrix(NA, ncol=2,nrow=length(unique(compare[which(compare$nSeqCDR3 %in% fw_df$nSeqCDR3),]$nSeqCDR3))))
            colnames(CDR3_growth) <- c("Growth", "VJCombo")
            rownames(CDR3_growth) <- unique(compare[which(compare$nSeqCDR3 %in% fw_df$nSeqCDR3),]$nSeqCDR3)
            for(i in 1:nrow(CDR3_growth)){
                fw_frac <- sum(fw_df[which(fw_df$nSeqCDR3==rownames(CDR3_growth)[i]),]$cloneFraction)
                compare_frac <- sum(compare[which(compare$nSeqCDR3==rownames(CDR3_growth)[i]),]$cloneFraction)
                CDR3_growth$Growth[i] <- fw_frac/compare_frac
                CDR3_growth$VJCombo[i] <- unique(fw_df[which(fw_df$nSeqCDR3==rownames(CDR3_growth)[i]),]$VJcombo)
            }

            CDR3_growth$VJ_Growth <- NA
            CDR3_growth$Ratio <- NA
            for(i in 1:nrow(CDR3_growth)){
                CDR3_growth$VJ_Growth[i] <- VJ_growth[which(rownames(VJ_growth)==CDR3_growth$VJCombo[i]),]
                CDR3_growth$Ratio[i] <- CDR3_growth$Growth[i]/CDR3_growth$VJ_Growth[i]
            }
            CDR3_growth <- CDR3_growth[which(CDR3_growth$VJ_Growth > 1),]
            assign(paste(patient, "CDR3_growth", sep="_"),CDR3_growth)
        }
    }
   
    files <- paste(patients, "CDR3_growth", sep="_")
    overall_growth <- data.frame()
    for(file in files){
       overall_growth <- rbind(overall_growth, eval(as.name(file)))
    }
    # Performs z-test with null hypothesis that VJ-growth and CDR3-growth are in a 1:1 ratio
    Ztest <- prop.test(cbind(overall_growth$Growth, overall_growth$VJ_Growth))
    Ztest 
}
