##############
# CDR3 per VJ #
##############

# Required Libraries: 
library (tidyverse)
library (ggraph)
library (igraph)
library (gridExtra)

# Calculates the CDR3 per VJ at each timepoint for a patient
# @param patient: Patient desired for analysis
# @param cohort: Sample cohort desired for analysis
# @param timepoint_order: Timepoint order desired for analysis

CDR3perVJ <- function(patient, cohort, timepoint_order){

    #Reading the input files:      
    #Concatenated file generated by '''Step2_TRBclonotype_txtFile_concatenation.R'''
    clonotypes <- clonotypes %>% 
            filter ( Patient_id %in% patient)%>%
            filter ( Cohort == cohort) %>%
            mutate(VJcombo = gsub("[.]", "_", VJcombo))

    # Remove unproductive clones from analysis and recompute clonefraction
    clonotypes <- clonotypes[-c(grep("[*]", clonotypes$aaSeqCDR3)),]
    clonotypes <- clonotypes[-c(grep("_", clonotypes$aaSeqCDR3)),]
    for(clone in 1:length(clonotypes$cloneFraction)){
        clonotypes$cloneFraction[clone] <- clonotypes$cloneCount[clone]/sum(clonotypes[which(clonotypes$Cycle==clonotypes$Cycle[clone]),]$cloneCount)
    }
    
    # Creates dataframe 'total_df' which contains the average CDR3 per VJ at each timepoint
    expanded_df <- clonotypes[which(clonotypes$cloneFraction >= 0),]
    timepoint_order <- timepoint_order[timepoint_order %in% unique(expanded_df$Cycle)] 
    total_df <- data.frame(matrix(NA,ncol=2, nrow=length(timepoint_order)))
    colnames(total_df) <- c("Cycle", "AverageCDR3")
    
    i <- 1
    for(cycle in timepoint_order){
        cycle_expanded <- expanded_df[which(expanded_df$Cycle==cycle),]
        AverageCDR3 <- length(cycle_expanded$aaSeqCDR3)/length(unique(cycle_expanded$VJcombo))
        total_df$Cycle[i] <- cycle
        total_df$AverageCDR3[i] <- AverageCDR3
        i <- i + 1
    }
    total_df <<- total_df
}
